name: boo_vie
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  http: ^0.13.4
  injectable: ^1.4.1
  logger: ^1.0.0
  stacked: ^2.1.7

dev_dependencies:
  auto_route_generator: ^3.2.3

  # Generators
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0

  # linting
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true

# Assets Example
#  assets:
#    - assets/images/
#
# Fonts Example
#  fonts:
#    - family: Open Sans
#      fonts:
#        - asset: assets/fonts/OpenSans-Italic.ttf
#          style: italic
#        - asset: assets/fonts/OpenSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/OpenSans-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/OpenSans-Light.ttf
#          weight: 300
#        - asset: assets/fonts/OpenSans-Regular.ttf
#          weight: 400
